export const ADD_AREA_FORM = "ADD_AREA_FORM";
export const EDIT_AREA_FORM = "EDIT_AREA_FORM";

export const ADD_CRAG_FORM = "ADD_CRAG_FORM";
export const EDIT_CRAG_FORM = "EDIT_CRAG_FORM";

export const ADD_JOURNAL_ENTRY_FORM = "ADD_JOURNAL_ENTRY_FORM";
export const EDIT_JOURNAL_ENTRY_FORM = "EDIT_JOURNAL_ENTRY_FORM";

export const ADD_JOURNAL_ENTRY_ROUTE_FORM = "ADD_JOURNAL_ENTRY_ROUTE_FORM";
export const EDIT_JOURNAL_ENTRY_ROUTE_FORM = "EDIT_JOURNAL_ENTRY_ROUTE_FORM";

export const ADD_ROUTE_FORM = "ADD_ROUTE_FORM";
export const EDIT_ROUTE_FORM = "EDIT_ROUTE_FORM";

export const AREA_PAGE = "AREA_PAGE";
export const CRAG_PAGE = "CRAG_PAGE";
export const JOURNAL_ENTRY_PAGE = "JOURNAL_ENTRY_PAGE";
export const JOURNAL_ENTRY_ROUTE_PAGE = "JOURNAL_ENTRY_ROUTE_PAGE";
export const ROUTE_PAGE = "ROUTE_PAGE";

export const CALENDAR_PAGE = "CALENDAR_PAGE";
export const SEARCH_PAGE = "SEARCH_PAGE";
