export const STARTUP = "STARTUP";
export const REFRESH_YEAR_ROUTES = "REFRESH_YEAR_ROUTES";

export const ADD_AREA = "ADD_AREA";
export const UPDATE_AREA = "UPDATE_AREA";

export const ADD_CRAG = "ADD_CRAG";
export const UPDATE_CRAG = "UPDATE_CRAG";

export const ADD_ROUTE = "ADD_ROUTE";
export const UPDATE_ROUTE = "UPDATE_ROUTE";

export const ADD_JOURNAL_ENTRY_ROUTE = "ADD_JOURNAL_ENTRY_ROUTE";
export const UPDATE_JOURNAL_ENTRY_ROUTE = "UPDATE_JOURNAL_ENTRY_ROUTE";

export const ADD_JOURNAL_ENTRY = "ADD_JOURNAL_ENTRY";
export const UPDATE_JOURNAL_ENTRY = "UPDATE_JOURNAL_ENTRY";