export const STARTUP = "STARTUP";
export const REFRESH_YEAR_ROUTES = "REFRESH_YEAR_ROUTES";

export const SHOW_AREA = "SHOW_AREA";
export const ADD_AREA = "ADD_AREA";
export const CANCEL_ADD_AREA = "CANCEL_ADD_AREA";
export const ADDED_AREA = "ADDED_AREA";
export const UPDATE_AREA = "UPDATE_AREA";
export const CANCEL_UPDATE_AREA = "CANCEL_UPDATE_AREA";
export const UPDATED_AREA = "UPDATED_AREA";
export const DELETED_AREA = "DELETED_AREA";

export const SHOW_CRAG = "SHOW_CRAG";
export const ADD_CRAG = "ADD_CRAG";
export const CANCEL_ADD_CRAG = "CANCEL_ADD_CRAG";
export const ADDED_CRAG = "ADDED_CRAG";
export const UPDATE_CRAG = "UPDATE_CRAG";
export const CANCEL_UPDATE_CRAG = "CANCEL_UPDATE_CRAG";
export const UPDATED_CRAG = "UPDATED_CRAG";
export const DELETED_CRAG = "DELETED_CRAG";

export const SHOW_ROUTE = "SHOW_ROUTE";
export const ADD_ROUTE = "ADD_ROUTE";
export const CANCEL_ADD_ROUTE = "CANCEL_ADD_ROUTE";
export const ADDED_ROUTE = "ADDED_ROUTE";
export const UPDATE_ROUTE = "UPDATE_ROUTE";
export const CANCEL_UPDATE_ROUTE = "CANCEL_UPDATE_ROUTE";
export const UPDATED_ROUTE = "UPDATED_ROUTE";
export const DELETED_ROUTE = "DELETED_ROUTE";

export const ADD_JOURNAL_ENTRY_ROUTE = "ADD_JOURNAL_ENTRY_ROUTE";
export const CANCEL_ADD_JOURNAL_ENTRY_ROUTE = "CANCEL_ADD_JOURNAL_ENTRY_ROUTE";
export const ADDED_JOURNAL_ENTRY_ROUTE = "ADDED_JOURNAL_ENTRY_ROUTE";
export const UPDATE_JOURNAL_ENTRY_ROUTE = "UPDATE_JOURNAL_ENTRY_ROUTE";
export const CANCEL_UPDATE_JOURNAL_ENTRY_ROUTE = "CANCEL_UPDATE_JOURNAL_ENTRY_ROUTE";
export const UPDATED_JOURNAL_ENTRY_ROUTE = "UPDATED_JOURNAL_ENTRY_ROUTE";
export const DELETED_JOURNAL_ENTRY_ROUTE = "DELETED_JOURNAL_ENTRY_ROUTE";

export const SHOW_JOURNAL_ENTRY = "SHOW_JOURNAL_ENTRY";
export const ADD_JOURNAL_ENTRY = "ADD_JOURNAL_ENTRY";
export const CANCEL_ADD_JOURNAL_ENTRY = "CANCEL_ADD_JOURNAL_ENTRY";
export const ADDED_JOURNAL_ENTRY = "ADDED_JOURNAL_ENTRY";
export const UPDATE_JOURNAL_ENTRY = "UPDATE_JOURNAL_ENTRY";
export const CANCEL_UPDATE_JOURNAL_ENTRY = "CANCEL_UPDATE_JOURNAL_ENTRY";
export const UPDATED_JOURNAL_ENTRY = "UPDATED_JOURNAL_ENTRY";
export const DELETED_JOURNAL_ENTRY = "DELETED_JOURNAL_ENTRY";

export const SHOW_SEARCH = "SHOW_SEARCH";
export const SHOW_CALENDAR = "SHOW_CALENDAR";